### PR TITLE
Removed duplicate idleTimeout multiplication by 1000 (fixes #6)

### LINKED ISSUE #6: idleTimeout is multiplied by 1000 twice
The `idleTimeout` parameter for the pool should be provided in seconds, but internally the `setTimeout` function works with milliseconds. So the value should be multiplied by 1000. But here it is done twice:

* First in `trireme-jdbc.js`: https://github.com/apigee/trireme-jdbc/blob/master/lib/trireme-jdbc.js#L85
* Then in `trireme-jdbc-pool.js`: https://github.com/apigee/trireme-jdbc/blob/master/lib/trireme-jdbc-pool.js#L35

As a result, if you use the default `idleTimeout`, which is 60, it means actually 60,000 seconds (more than 16 hours).

### PR DESCRIPTION
**Pull request by ivan-novakov**

### CODE REVIEW

**Comment by gbrail** [comment]
Thanks for catching this!

Rebased and merged to master.

**Comment by gbrail** [comment]
Thanks for the fixes!

I merged them to master. Can you test them yourself? Assuming that the
merge is OK for you, I will publish a new release to NPM.

On Mon, Nov 30, 2015 at 4:15 AM, Ivan Novakov <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apigee/trireme-jdbc/pull/7
> Commit Summary
>
>    - Removed duplicate idleTimeout multiplication by 1000 (fixes #6)
>
> File Changes
>
>    - *M* lib/trireme-jdbc.js
>    <https://github.com/apigee/trireme-jdbc/pull/7/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/apigee/trireme-jdbc/pull/7.patch
>    - https://github.com/apigee/trireme-jdbc/pull/7.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme-jdbc/pull/7>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by ivan-novakov** [comment]
@gbrail I tested the merge and it's OK, thanks!

**Comment by gbrail** [comment]
OK, and thanks for the help! 

I published 1.0.1 to NPM just now.

**Pull request closed without merging**
